# Generated by Django 3.1.3 on 2020-11-16 10:50

from django.db import migrations, models
import django.db.models.deletion
import djchoices.choices


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='InDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(auto_now_add=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(choices=[('D', 'Doctor'), ('A', 'Assistant'), ('N', 'Nurse')], max_length=10, validators=[djchoices.choices.ChoicesValidator({'A': 'Assistant', 'D': 'Doctor', 'N': 'Nurse'})])),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('in_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.indepartment')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(auto_now_add=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.employee')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.role')),
            ],
        ),
    ]
