# Generated by Django 3.1.3 on 2020-11-18 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_auto_20201117_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='clinic_id',
            new_name='clinic',
        ),
    ]
