# Generated by Django 3.1.3 on 2020-11-16 10:50

from django.db import migrations, models
import django.db.models.deletion
import djchoices.choices


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        ('clinic', '0003_employeerole_indepartment_role_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_url', models.CharField(max_length=255)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[], max_length=10, validators=[djchoices.choices.ChoicesValidator({})])),
            ],
        ),
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.document')),
                ('in_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.indepartment')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.documenttype'),
        ),
        migrations.AddField(
            model_name='document',
            name='in_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.indepartment'),
        ),
        migrations.AddField(
            model_name='document',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
        migrations.AddField(
            model_name='document',
            name='patient_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientcase'),
        ),
    ]
